### ISSUE TITLE
Can this library support SSL?

### ISSUE THREAD

**Issue by kahwooi** [bojand/grpc-caller#1]
Would like to have some example of using it with SSL.

**Comment by bojand** [comment]
This module just wraps the normal grpc Node.js module. It should support everything gRPC supports regarding SSL. You can pass options just like you would with the normal gRPC client. Some relevant documentation: 

https://grpc.io/docs/quickstart/node.html#update-the-client
https://grpc.io/docs/tutorials/basic/node.html#creating-the-client
https://grpc.io/grpc/node/grpc.Client.html
https://grpc.io/grpc/node/grpc.credentials.html

Normally gRPC would be used in service-to-service communication once the outside request is inside the "application" which would be comprised of multiple services, and thus at that point auth (from transport / ssl perspective) has been done; so at this point you could use insecure requests. Also traditionally Node.js isn't the most performant platform for direct SSL connections, but that may have changed in recent times.
