### ISSUE TITLE
Passing Grpc proto load options to caller constructor

### ISSUE THREAD

**Issue by dannypaz** [bojand/grpc-caller#14]
Is it currently possible to be able to pass [grpc load options](https://grpc.io/grpc/node/grpc.html#.load__anchor) to the `caller` constructor?

**Comment by dannypaz** [comment]
I was able to load grpc options (like `convertFieldsToCamelCase: true`, by loading grpc first and then passing in the applicable service into `caller`.

Example:
```
const grpc = require('grpc')
const options = { convertFieldsToCamelCase: true }
const myProtoPath = path.resolve('path.to.my.proto.file')
const proto = grpc.load(myProtoPath, 'proto', options)
const client = caller('MyRpcHost:1337', myProtoPath.MyServiceName)
```

**Comment by bojand** [comment]
Yes for now this is the only way to do it. I will try and look into adding this.

**Comment by nouh** [comment]
really need to add options to caller.
