### ISSUE TITLE
Are the examples in the docs supposed to work?

### ISSUE THREAD

**Issue by vaskevich** [bojand/grpc-caller#17]
Hi there,

I'm confused how some of these examples are to work:

```js
client.sayHello({ name: 'Bob' })
  .then(res => console.log(res))
```

I'm using gRPC with protoc, and each of the methods on the original generated client requires a specific message instance. So instead, I'd have to do something like:

```js
const message = new HelloMessage();
message.setName('Bob');
client.sayHello(message)
  .then(res => console.log(res))
```

Are the examples just supposed to be pseudocode, or is there a way of enabling the nicer syntax that I'm not aware of? Thanks!

**Comment by bojand** [comment]
Hello, if you create the client dynamically then it will work as [evident in the tests](https://github.com/bojand/grpc-caller/blob/master/test/basics.test.js#L104). If you use pre-generated grpc code to create the client, then you have to use the actual pregenerated Message classes. Example in [tests](https://github.com/bojand/grpc-caller/blob/master/test/basics.test.js#L127).
