### ISSUE TITLE
Retries do not support backoff

### ISSUE THREAD

**Issue by TimFerrell** [bojand/grpc-caller#20]
When calling a service with the `retry` option, it will immediately make a retry request after the first failure:
https://github.com/bojand/grpc-caller/blob/549484c9ded7412490b95da9dd9db75afa00cfbc/lib/client.js#L47-L64

General guidance is to implement backoffs when retrying to prevent overloading the server. 

The suggestion is to support a function that returns the amount of time to delay before attempting the retry. This approach would support different approaches to backoffs (constant value, linear, exponential, jitter, no jitter).

Something similar to this:
```js
/**
 * @param {number} requestAttempts Amount of times that the request has been made.
 */
function backoff(requestAttempts) {
  return (requestAttempts * 20);
}
```

**Comment by bojand** [comment]
The `retry` option is just [`async.retry()`](http://caolan.github.io/async/docs.html#retry). So you could do:

```js
const res = await client.sayHello({ name: 'Bob' }, {}, { retry: { times: 3, interval: 200 } })
console.log(res)
```
and that will do retries with 200 milliseconds between retry intervals.

You can also indeed use a function as well:

```js
const res = await client.sayHello({
  name: 'Bob'
}, {}, {
  retry: {
    times: 10,
    interval: function(retryCount) {
      return 50 * Math.pow(2, retryCount);
    }
  }
}) 

console.log(res)
```

Is this not working for you?

**Comment by TimFerrell** [comment]
That works! Thanks for the reply, and my apologies for not catching this myself.
