### ISSUE TITLE
Expose protoLoader options to caller

### ISSUE THREAD

**Issue by TimFerrell** [bojand/grpc-caller#22]
# Summary
In `0.7.0` the default behavior of `grpc-caller` returned default values and kept case, without conversion to camelCase.

Starting with `0.8.0` these defaults changed, resulting in an empty object (if only defaults were returned from the server), and also introduced the expectation that arguments provided to the client are in camelCase instead of the field name in the message defintion.

For example, `user_id` is expected to be provided to the client as `userId` in `0.8.0`.

# Request

Expose the `loadOptions` that is declared within the constructor to allow input via arguments, so that the previous behavior can be achieved.
https://github.com/bojand/grpc-caller/blob/master/lib/index.js#L43-L50

**Comment by bojand** [comment]
Should be doable in `0.9.0`. 

```js
const file = path.join(__dirname, 'helloworld.proto')
const load = {
  //, ... any other load otpions 
}
const client = caller('localhost:50051', { file, load }, 'Greeter')
```
