### ISSUE TITLE
The introduction of proto-loader causes breaking changes

### ISSUE THREAD

**Issue by yoitsro** [bojand/grpc-caller#24]
Since the introduction of `@grpc/proto-loader`, breaking changes are introduced due to the default options that module uses.

I would suggest you either perform a major version bump and provide an npm warning to users who consume versions of `grpc-caller` since the change was introduced, or you maintain the previous functionality by passing in default options as shown on https://github.com/grpc/grpc-node/tree/master/packages/grpc-protobufjs

```javascript
const options = {
  keepCase: true,
  longs: String,
  enums: String,
  defaults: true,
  oneofs: true
}
```

**Comment by bojand** [comment]
Hello,

I realize the issue and understand the inconvenience and the frustration. grpc-caller is < 1.0.0, which in terms of semver means [anything may change at any time](https://semver.org/#spec-item-4). Nevertheless we do try and follow the [common practice](https://docs.npmjs.com/misc/semver):

> Many authors treat a 0.x version as if the x were the major "breaking-change" indicator.

The `@grpc/proto-loader` dependency was introduced in [0.7.0 -> 0.8.0](https://github.com/bojand/grpc-caller/compare/v0.7.0...v0.8.0), making it a "breaking change" in that sense. Maybe we could have done a better job of doing it in a backwards compatible way, but it's difficult as the underlying grpc node module is a bit of a moving target itself and some of it was not documented as well at the time; so this is the best we can do for now.

**Comment by yoitsro** [comment]
Ahh! I see. Somehow, in the 6 years of working with Node, I've somehow never realised that a minor version change on a major version of 0 can be a breaking change! Thanks for the education :) and again, thanks for the package!

I'll close this.
