### ISSUE TITLE
Not work with package name

### ISSUE THREAD

**Issue by akleandrov** [bojand/grpc-caller#27]
If proto file contains package name, services not find.
Error: 12 UNIMPLEMENTED: RPC method not implemented /config.ConfigService/sendConfig
`const PROTO_PATH = path.join(__dirname, '..', 'proto', 'main.proto');
const ConfiguratorHost = config.services.configurator;
const client = caller(ConfiguratorHost, PROTO_PATH, 'ConfigService');`

`syntax = "proto3";
package config;
service ConfigService {
  rpc sendConfig(ConfigRequest) returns (NullResponse);
  rpc writeSystemDeviceInfo (SystemDeviceInfo) returns (NullResponse);
}`

**Comment by bojand** [comment]
Please provide a reproducible example as that's an error that would be returned by the server.
https://grpc.io/docs/guides/error.html
