### ISSUE TITLE
Clearly document how to read a streaming response

### ISSUE THREAD

**Issue by stephen-dahl** [bojand/grpc-caller#28]
Please add a code example of reading a response stream to the docs.

**Comment by bojand** [comment]
Hello, thanks for submitting the issue. What's missing exactly and can you provide some more info on what's the challenge? Server streaming and bidirectional calls are unchanged from response semantics perspective so everything is the same as the underlying grpc client. The [official documentation](https://grpc.io/docs/tutorials/basic/node.html#streaming-rpcs) demonstrates the usage sufficiently. There are also the [tests](https://github.com/bojand/grpc-caller/blob/master/test/resstream.test.js) that can serve as example; but I do not see what additional information needs to be documented that's not present in the official grpc documentation?

**Comment by stephen-dahl** [comment]
I see how it works now (though isn't working in my code yet)
your readme has the "Improved request stream/response calls" section but all your examples there only show how to stream out and receive a singular response. I think it would be helpful to add a code sample there for reading a streaming response with something like

```
//call is a readable stream
const call = client.listStuff({ message: 'Hello' })
call.on('data', message => console.log(message))
call.on('end', () => console.log('all data recieved'))
```
Also, it isn't obvious what a streaming request and response looks like. maybe add another snippet labeling the request and response streams for a call.

Finally, maybe a statement saying to look at tests for more examples.

**Comment by stephen-dahl** [comment]
for duplex maybe
```
//call is a duplex stream
const call = client.listStuff({ message: 'Hello' })
call.on('data', message => console.log(message))
call.on('end', () => console.log('all data recieved'))
call.write(message)
call.write(message2)
```

**Comment by bojand** [comment]
Hello, thanks for the clarification. I see the source of confusion with the wording. `Improved request stream/response calls` is really talking about client streaming calls. I will improve the readme and make it clearer that server streaming and duplex are unchanged, and add a basic example and context. Thanks.
