### ISSUE TITLE
Is it a pure js module for grpc?

### ISSUE THREAD

**Issue by xeoshow** [bojand/grpc-caller#32]
Hello, 

I am new to grpc-caller, just would like to know if it is a pure js module with no need to compile native dependency things?

Thanks a lot.

Best regards, Jason

**Comment by bojand** [comment]
Hello, this just wraps the Node.js [grpc module](https://www.npmjs.com/package/grpc), and requires it as a [peer dependency](https://github.com/bojand/grpc-caller/blob/master/package.json#L39).

**Comment by xeoshow** [comment]
Thanks for kind reply!

I am new to nodejs, For the nodejs official version 8.6.0, is the grpc module shipped as default within Nodejs? Or, could I use grpc-caller directly in the official nodejs 8.6.0? 

Sorry bothering for the newbie question, and thanks again!

Best regards, Jason

**Comment by bojand** [comment]
Hello, I am not really sure I understand the question. Node.js is just the runtime / platform. You would have to include both `grpc` and `grpc-caller` as dependencies in your project's [`package.json`](https://docs.npmjs.com/files/package.json) file, and then install them using `npm install`. It should work fine with Node.js 8.6.0.

**Comment by bojand** [comment]
As far as I know that usually depends on the combination of Node.js version, OS and architecture. Normally first it tries to download prebuilt binary for the specific combination of Node.js OS and architecture (which should work for most common ones for Node 8). If it cannot find the appropriate prebuilt library it tries to build and compile the native parts using gyp and related tooling (which come with Node.js).

**Comment by xeoshow** [comment]
Actually I am trying to use grpc based in the below project, which is nodejs for mobile like Android. Since the support for gyp is not good for it, and also not sure if has the default grpc binary, so asked this question. I will try them these days and report back.
https://github.com/janeasystems/nodejs-mobile
