### ISSUE TITLE
What is serviceWrapper in the static example?

### ISSUE THREAD

**Issue by beautycss** [bojand/grpc-caller#38]
I'm using static client with metadata, tried codes below but didn't work.
```
const HelloService = require('./static/Hello_grpc_pb');
const client = caller('localhost: 50051', HelloService.HelloServiceClient);
const result = await HelloService.queryList({ name: 'tom' }, { node_id: 1 });
```

```
const HelloService = require('./static/Hello_grpc_pb');
let client = caller('localhost: 50051', HelloService.HelloServiceClient);
client = caller.wrap(client, { node_id: 1 });
const result = await HelloService.queryList({ name: 'tom' });
```

`{ node_id: 1 }` is my metadata.

![image](https://user-images.githubusercontent.com/16473160/58923087-aec8e880-8770-11e9-9c61-e4bc39090e24.png)

I can't understand what is `serviceWrapper` in the document, how to define it?

Thanks!

**Comment by bojand** [comment]
Hello the documentation here was misleading. It's been updated. Thanks for pointing this out.

**Comment by beautycss** [comment]
Nice! 👍

But I'm still confused about adding metadata with caller in static example.

code without metadata works well:
```
const messages = require('./static/helloworld_pb');
const services = require('./static/helloworld_grpc_pb');
const request = new messages.HelloRequest();
const client = caller('localhost:50051', services.GreeterClient);
const result = await client.sayHello(request);
console.log('result', result.getMessage());
```

code with metadata doesn't work:
eithor:
```
const services = require('./static/helloworld_grpc_pb');
const credentials = grpc.credentials.createInsecure();
const client = caller('localhost:50051', services.GreeterClient, credentials, {}, { node_id: 1 });
```
or:
```
const result = await client.sayHello(request, { node_id: 1 });
```

my metadata is `{ node_id: 1 }`

Can u show where to put metadata in static example?

Thanks!

**Comment by bojand** [comment]
Hello, you can use `caller.wrap()` to wrap an existing client instance:

```js
const messages = require('./static/helloworld_pb')
const services = require('./static/helloworld_grpc_pb')

const interceptor = (options, nextCall) =>
  new grpc.InterceptingCall(nextCall(options), {
    sendMessage: (message, next) => {
      const name = message.getName()
      message.setName(name + 2)
      next(message)
    }
  })

const options = grpc.credentials.createInsecure()
options.interceptors = [interceptor]

// create grpc client with insecure option and client side interceptor
const serviceClient = new services.GreeterClient(TEST_HOST, options) 

// wrap the grpc client and add default metadata to all calls
const client = caller.wrap(serviceClient, { foo: 'bar' }, options)

const request = new messages.HelloRequest()
request.setName('Bob')

// make the call, also adding request metadata
const response = await client.sayHello(request, { ping: 'meta' })
console.log(response.getMessage())
```

Hope this helps.

**Comment by beautycss** [comment]
Thanks a lot! This do help me! It works! 👍👍👍

**Comment by beautycss** [comment]
Hi, I need your help again. 😄😂

I'm trying to get metadata and status from the response but can't get them, the codes are the same as above.

I find that there's Request API in the document, it says "The API can only be used for Unary and request streaming calls". So does it support static example?

**Comment by beautycss** [comment]
> Hi, Does Request API support static example?
> 
> I'm trying to get `metadata` and `status` from the response but can't get them.
> 
> I find Document says "The API can only be used for Unary and request streaming calls".
> 
> ```js
> const options = grpc.credentials.createInsecure();
> const messages = require(`./static/helloworld_pb`);
> const services = require(`./static/helloworld_grpc_pb`);
> const request = new messages.HelloRequest();
> const client = caller('localhost:50051', services.GreeterClient);
> const clientMetadata = { a: 1 };
> 
> const req = new client
>   .Request('sayHello', request)
> //  .Request('sayHello')
> //  .withGrpcOptions(request)
>   .withMetadata(clientMetadata)
>   .withResponseMetadata(true)
>   .withResponseStatus(true)
>   .withRetry(5)
> const res = await req.exec();
> 
> console.log(res.response);
> console.log(res.metadata);
> console.log(res.status);
> ```
> 
> ```js
> const res = await client.sayHello({ name: 'Bob' }, {}, { retry: 3, responseStatus: true, responseMetadata: true })
> console.log(res)
> ```
> 
> I tried the static with Request API and normal but doesn't work. 😂
> 
> Thanks!

```js
//  const client = caller.wrap(serviceClient, requestMetadata, { retry: 3, ... }); // wrong if add options
  const client = caller.wrap(serviceClient, requestMetadata); // right without options
  const req = new client
  .Request('sayHello', request)
   .withMetadata(requestMetadata)
   .withResponseMetadata(true)
   .withResponseStatus(true)
   .withRetry(5)
  const res = await req.exec();
  console.log('res', res);
```

Finally work out with Request API. 😂😂
After a lot of tries, I find that the wrap call options should be deleted. 😂😂😂
