### ISSUE TITLE
Question - TypeScript support and type declarations

### ISSUE THREAD

**Issue by kabirbaidhya** [bojand/grpc-caller#45]
I'm trying to use this in my TS project but I couldn't find the type declarations. Is TS not supported yet? 

In case this isn't already there, I'm willing to do a PR to add type defs. Please let me know. Thanks.

**Comment by aaswtest** [comment]
any update on this being supported in TS

**Comment by bojand** [comment]
Hello, sorry this fell through without any attention. I do not use typescript and do not have much practical knowledge with it. A PR would be welcome.
