### ISSUE TITLE
replace `grpc` with `grpc-js`?

### ISSUE THREAD

**Issue by seoker** [bojand/grpc-caller#51]
As [official stated](https://grpc.io/blog/grpc-js-1.0/), the grpc package is planned to be deprecated, just wondering if the changes will be applied to this package?

It will be nice if there's a native-binary-free version to save the troublesome deployment stuff.

**Comment by eeston** [comment]
FYI I've published a version of `grpc-caller` that is `@grpc/grpc-js` compatible as my [PR has gone a bit stale...](https://github.com/bojand/grpc-caller/pull/55)

[GitHub](https://github.com/eeston/grpc-caller)
[npm](https://www.npmjs.com/package/@eeston/grpc-caller)


Happy to push the changes back upstream if/when the PR gets approved...

**Comment by seoker** [comment]
close this one since it seems to be implemented in 3dbce274c18e769cb5ff7a9da21e9642ebd22a30
